<?php

namespace ThousandMonkeys\LibraryBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class VersionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ThousandMonkeys\LibraryBundle\Controller\VersionController();
        return $instance;
    }
}
